### ISSUE TITLE
Dynamic FBO scaling does not seem to work

### ISSUE THREAD

**Issue by Romanito** [jimbo00000/RiftRay#1]
Hi, I'm very enthusiastic about this project, the work you've done so far is great!

I did some tests with FBO scaling in the last version (2.0.1) using the DynamicallyScaleFBO and FboMinimumScale parameters, but I couldn't get it to work how I wanted. Actually, the program seems to always use the minimum scale, even if a higher one would be fine. Ex: on my computer some shaders run perfectly with FboMinimumScale=0.8, but if I set it to 0.25 it will use 0.25.

Maybe the target framerate (100) is too high? 75 should be fine for the DK2.

As a workaround, it would be nice to manually tune the scale factor at runtime with shortcut keys, and save the set value for each shader.

What do you think?

**Comment by jimbo00000** [comment]
Hi, thanks for the interest and for creating this issue.

Sure, we can do a manual adjustment using a shortcut key. Which keys would you like to bind it to?

I should also mention in the docs that RiftRay runs best(for me and for now) with vsync turned off. If you keep your graphics settings on app-determined vsync as depicted below, glfw can toggle vsync programmatically and the buttons in the VSync section of the auxiliary control panel(press `) will work.

![nvidiacontrolpanel-vsync](https://cloud.githubusercontent.com/assets/5005203/5275875/ea354b32-7a7a-11e4-86e5-2ef30c7fd214.png)
![amdcontrolpanel-vsync](https://cloud.githubusercontent.com/assets/5005203/5275876/ec2c5fde-7a7a-11e4-9c91-9a1d0cc52c35.png)
The performance tuning code works better for me when the render loop has the freedom to take non-multiple-of-16.6ms times, but this comes at the cost of tearing(which can be visible and annoying). What looks best for you? I'd like to find out what a "typical" system's settings look like so at startup the app can find the best possible configuration.

For the time being, there are also driver and hardware vsync issues to contend with, and these may interact with the still nascent Direct HMD Access Mode. I wouldn't be surprised if this were in flux for a while, particularly across different platforms.

**Comment by Romanito** [comment]
Thanks for the tip. My global setting for vsync is already app-determined anyway, and I didn't notice tearing so far.

As for the key bindings, I guess any keys will be fine. This app uses F5-F8: http://www.reddit.com/r/oculus/comments/2nv4kf/new_build_of_shadertoy_vr_app_20141130/

**Comment by jimbo00000** [comment]
OK, added. You can now adjust the FBO resolution manually with keys(F5/F8 for coarse adjustment, F6/F7 for fine). I've turned off the dynamic FBO scaling in the config file while I investigate better strategies for dynamic adjustment with vsync on.

**Comment by jimbo00000** [comment]
After a long delay, tweakbar resolution in-scene is now independent from shader resolution. This along with mouse and gamepad controls should allow for a much more comfortable performance adjusting experience.

The latest SDK 0.5.0.1 seems to force vsync on for client path distortion, and this may break dynamic FBO scaling. If you'd still like to try it, turn vsync off, use the client path(F4), and set your target framerate to about 100 fps.
