### ISSUE TITLE
Health And Safety warning never disappears

### ISSUE THREAD

**Issue by anastasiuspernat** [jimbo00000/RiftRay#2]
How do you make the warning disappear in the beginning? It always stays on the screen no matter what. I'm using keyboard.

**Comment by jimbo00000** [comment]
The SDK will only allow the warning to be dismissed after a 6 second interval has elapsed from the start of the app(2 seconds in debug mode). After that time, pressing any key or tapping the HMD will dismiss the warning. Does the warning stay up for you after 6 seconds?

Relevant lines are [here](https://github.com/jimbo00000/RiftRay/blob/master/src/AppSkeleton/RiftAppSkeleton.cpp#L449) and [here](https://github.com/jimbo00000/RiftRay/blob/master/src/glfw_main.cpp#L125)

**Comment by anastasiuspernat** [comment]
Yes, it stays forever. 
What makes it go away is shaking my head, strangely

**Comment by jimbo00000** [comment]
As of release 2.2, there are a lot more calls to ovrHmd_DismissHSWDisplay: on any key press, gamepad button press or mouse button press, as well as a tap on the HMD(or a shake of the head). There is also currently no HSW for now in the client path(F4).

Please re-open the issue if the HSW does not disappear after 6 seconds from app launch and user input.
