### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by iMartyn** [jimbo00000/RiftRay#3]
Now that CV1 is out, and you've updated a whole load of stuff  to work with the new sdk, can those of us who don't want to load up the whole of VS up and running get a new release?  It'd be really cool to play with this on my dk2 but I've not hooked up to this install and now only have the choice of current runtime.

Pretty please? ;-)

**Comment by jimbo00000** [comment]
How did I forget to do that? ;)

https://github.com/jimbo00000/RiftRay/releases/tag/3.1.0

Let me know if I've missed any shadertoys! Or convert your own - http://jimbo00000.github.io/opengl/portable/glsl/riftray/2016/01/06/riftray-hackingshaders.html

**Comment by iMartyn** [comment]
Awesome, will give it a play later this week.  Thanks for the fast turnaround!
